#!/bin/bash
if [ ${#} -ne 2 ]; then
     >&2 echo "error"
     exit 1
fi
for word in $(cat $1);do 
     if [ -e ${word}.args ];then
            if [ ! -e ${word}.out ]; then
               >&2 echo "error"
               exit 1
            elif [ ! -r ${word}.out ]; then 
               >&2 echo "error"
               exit 1
            else 
               ./$2 $(cat ${word}.args) | cmp -s ${word}.out 
               if [ ${?} -ne 0 ]; then
                   echo "Test failed: ${word}"
                   echo "Args:"
                   cat ${word}.args
                   echo "Expected:"
                   cat ${word}.out
                   echo "Actual:"
                   ./$2 $(cat ${word}.args)
               fi
            fi
     else 
            if [ ! -e ${word}.out ]; then
               >&2 echo "error"
               exit 1
            elif [ ! -r ${word}.out ]; then
               >&2 echo "error"
               exit 1
            else
               ./$2 | cmp -s ${word}.out 
               if [ ${?} -ne 0 ]; then
                   echo "Test failed: ${word}"
                   echo "Args:"
                   echo "Expected:"
                   cat ${word}.out
                   echo "Actual:"
                   ./$2
               fi
            fi
    fi
done
